# Generated by Django 3.2.5 on 2021-09-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_wishlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
