# Generated by Django 3.2.5 on 2021-09-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_remove_wishlist_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
