# Generated by Django 3.2.5 on 2021-09-16 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default=(('d', 'Draft'), ('p', 'Published')), max_length=1),
        ),
    ]
