# Generated by Django 3.2.5 on 2021-09-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
