# Generated by Django 3.2.5 on 2021-09-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articlecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.ArticleCategory'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Show?'),
        ),
    ]
