# Generated by Django 3.2.5 on 2021-09-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210917_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='Select Category', on_delete=django.db.models.deletion.CASCADE, to='blog.articlecategory'),
        ),
    ]
