# Generated by Django 3.2.5 on 2021-07-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210729_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='maincategory',
        ),
    ]
