# Generated by Django 3.2.5 on 2021-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='please write short description about this proudct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='please write all thing about this proudct'),
        ),
    ]
