# Generated by Django 3.2.5 on 2021-09-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.FloatField(default=0),
        ),
    ]
